# Generated by Django 2.2.3 on 2019-07-21 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_attendance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_post', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('password', models.IntegerField()),
                ('email', models.TextField()),
                ('blood_group', models.CharField(max_length=2)),
                ('phone_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='dues',
            new_name='due',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
        migrations.DeleteModel(
            name='event_details',
        ),
        migrations.DeleteModel(
            name='members',
        ),
    ]
