# Generated by Django 2.2.3 on 2019-08-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseapp', '0004_auto_20190807_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RGM_name', models.CharField(max_length=20)),
                ('RGM_date', models.DateField()),
                ('RGM_time', models.DateField()),
                ('created_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RGM_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RGM_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='due',
            old_name='user',
            new_name='Membership_id',
        ),
        migrations.RenameField(
            model_name='event_detail',
            old_name='event_name',
            new_name='Event_name',
        ),
        migrations.RenameField(
            model_name='event_detail',
            old_name='event_attendance',
            new_name='Event_number',
        ),
        migrations.RenameField(
            model_name='event_detail',
            old_name='user',
            new_name='Membership_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='Member_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_post',
            new_name='Member_post',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='password',
            new_name='Membership_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone_number',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='due',
            name='month_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='userid',
        ),
        migrations.AddField(
            model_name='member',
            name='Email',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='Phone_Number',
            field=models.IntegerField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='Roll_Number',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
        ),
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
