# Generated by Django 2.2.3 on 2019-08-10 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0005_auto_20190810_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
