# Generated by Django 2.2.3 on 2019-08-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0006_auto_20190810_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rgm_attendance',
            old_name='RGM_number',
            new_name='Membership_id',
        ),
    ]
